// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQRnteuC9iMdnSXoh1ChF6ZszmwwsVbNQ',
    appId: '1:231144467688:web:8465e4221e4a7d3378ed5d',
    messagingSenderId: '231144467688',
    projectId: 'flutter-app-d83c1',
    authDomain: 'flutter-app-d83c1.firebaseapp.com',
    storageBucket: 'flutter-app-d83c1.appspot.com',
    measurementId: 'G-TWRJD45XGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIqvSIvf-oG-8Kh99tfF02jkJ8GMCfX4s',
    appId: '1:231144467688:android:220acdd13701035978ed5d',
    messagingSenderId: '231144467688',
    projectId: 'flutter-app-d83c1',
    storageBucket: 'flutter-app-d83c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtIMyX0VY3tYtMBlL-ss9cbIZkltkyTrU',
    appId: '1:231144467688:ios:9124c0e3d0a49f6c78ed5d',
    messagingSenderId: '231144467688',
    projectId: 'flutter-app-d83c1',
    storageBucket: 'flutter-app-d83c1.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtIMyX0VY3tYtMBlL-ss9cbIZkltkyTrU',
    appId: '1:231144467688:ios:35dd09b5f9ccd9e778ed5d',
    messagingSenderId: '231144467688',
    projectId: 'flutter-app-d83c1',
    storageBucket: 'flutter-app-d83c1.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
